export const TASKS_ARCHIVE_TASKS_OPEN = 'TASKS_ARCHIVE_TASKS_OPEN';

export const TASKS_ARCHIVE_TASKS_CHANGE_PAGE = 'TASKS_ARCHIVE_TASKS_CHANGE_PAGE';

export const TASKS_ARCHIVE_TASKS_REMOVE_TASK = 'TASKS_ARCHIVE_TASKS_REMOVE_TASK';
