export const TASKS_CURRENT_TASKS_OPEN = 'TASKS_CURRENT_TASKS_OPEN';

export const TASKS_CURRENT_TASKS_CHANGE_PAGE = 'TASKS_CURRENT_TASKS_CHANGE_PAGE';

export const TASKS_CURRENT_TASKS_COMPLETE = 'TASKS_CURRENT_TASKS_COMPLETE';
