// AppBoard
export const SQUARES_FILL = 'SQUARES_FILL';
export const SINGLE_ITEM_SQUARES_FILL = 'SINGLE_ITEM_SQUARES_FILL';
export const SQUARES_RELEASE = 'SQUARES_RELEASE';

// alerts
export const ALERT_SET = 'ALERT_SET';
export const ALERT_REMOVE = 'ALERT_REMOVE';

// dragged item
export const DRAGGED_ITEM_SET = 'DRAGGED_ITEM_SET';
export const DRAGGED_ITEM_RELEASE = 'DRAGGED_ITEM_RELEASE';

// hovered squares
export const HOVERED_SQUARES_SET = 'HOVERED_SQUARES_SET';
export const HOVERED_SQUARES_REMOVE = 'HOVERED_SQUARES_REMOVE';

// equipped items
export const EQUIPPED_ITEM_SET = 'EQUIPPED_ITEM_SET';
export const EQUIPPED_ITEMS_SET = 'EQUIPPED_ITEMS_SET';
export const EQUIPPED_ITEM_REMOVE = 'EQUIPPED_ITEM_REMOVE';

