// AppBoard
export const SQUARES_FILL = 'SQUARES_FILL';
export const SINGLE_ITEM_SQUARES_FILL = 'SINGLE_ITEM_SQUARES_FILL';
export const SQUARES_RELEASE = 'SQUARES_RELEASE';
export const EQUIPPED_STATE_CHANGE = 'EQUIPPED_STATE_CHANGE';
export const BOARD_CURRENT_COUNT_CHANGE = 'BOARD_CURRENT_COUNT_CHANGE'; //board item current count change
export const BOARD_ALL_ITEMS_RELEASE = 'BOARD_ALL_ITEMS_RELEASE';

export const BOARD_SET_SQUARE_SIZE = 'BOARD_SET_SQUARE_SIZE';

// dragged item
export const DRAGGED_ITEM_SET = 'DRAGGED_ITEM_SET';
export const DRAGGED_ITEM_RELEASE = 'DRAGGED_ITEM_RELEASE';
export const GOING_TO_DROP_SET = 'GOING_TO_DROP_SET';

// hovered squares
export const HOVERED_SQUARES_SET = 'HOVERED_SQUARES_SET';
export const HOVERED_SQUARES_REMOVE = 'HOVERED_SQUARES_REMOVE';

// equipped items
export const EQUIPPED_ITEM_SET = 'EQUIPPED_ITEM_SET';
export const EQUIPPED_ITEMS_SET = 'EQUIPPED_ITEMS_SET';
export const EQUIPPED_ITEM_REMOVE = 'EQUIPPED_ITEM_REMOVE';
export const EQUIPPED_CURRENT_COUNT_CHANGE = 'EQUIPPED_CURRENT_COUNT_CHANGE';
export const EQUIPPED_ALL_ITEMS_RELEASE = 'BOARD_ALL_ITEMS_RELEASE';

// context menu
export const CONTEXT_MENU_OPEN = 'CONTEXT_MENU_OPEN';
export const CONTEXT_MENU_CLOSE = 'CONTEXT_MENU_CLOSE';
export const CONTEXT_MENU_SPLIT_OPEN = 'CONTEXT_MENU_SPLIT_OPEN';

// hovered item
export const HOVERED_ITEM_ADD = 'HOVERED_ITEM_ADD';
export const HOVERED_ITEM_REMOVE = 'HOVERED_ITEM_REMOVE';
