export const PERMISSIONS_ROLES_PERMISSIONS_SET = 'PERMISSIONS_ROLES_SET';

export const PERMISSIONS_ROLE_SELECT = 'PERMISSIONS_ROLE_SELECT';
export const PERMISSIONS_ROLE_REMOVE = 'PERMISSIONS_ROLE_REMOVE';

export const PERMISSIONS_COMMON_PERMISSION_CHANGE = 'PERMISSIONS_COMMON_PERMISSION_CHANGE';

export const PERMISSIONS_TAB_OPEN = 'PERMISSIONS_TAB_OPEN';