export const CORPORATIONS_OPEN = 'CORPORATIONS_OPEN';
export const CORPORATIONS_CLOSE = 'CORPORATIONS_CLOSE';

export const CORPORATIONS_SET_LOADING = 'CORPORATIONS_SET_LOADING';

export const CORPORATIONS_TAB_OPEN = 'CORPORATIONS_TABS_OPEN';
