export const CORPORATIONS_TREASURY_OPEN = 'CORPORATIONS_TREASURY_OPEN';


export const CORPORATIONS_TREASURY_CHANGE_AVAILABLE_AMOUNT = 'CORPORATIONS_TREASURY_CHANGE_AVAILABLE_AMOUNT';

export const CORPORATIONS_TREASURY_WITHDRAW_MONEY = 'CORPORATIONS_TREASURY_WITHDRAW_MONEY';
export const CORPORATIONS_TREASURY_PUT_MONEY = 'CORPORATIONS_TREASURY_PUT_MONEY';
export const CORPORATIONS_TREASURY_TRANSFER_MONEY = 'CORPORATIONS_TREASURY_TRANSFER_MONEY';



