export const STAFF_STAFF_OPEN = 'STAFF_STAFF_OPEN';

export const STAFF_STAFF_CHANGE_PAGE = 'STAFF_STAFF_CHANGE_PAGE';

export const STAFF_STAFF_REMOVE_FROM_ROLE = 'STAFF_STAFF_REMOVE_FROM_ROLE';

export const STAFF_STAFF_ADD_TO_ROLE = 'STAFF_STAFF_ADD_TO_ROLE';

export const STAFF_STAFF_KICK = 'STAFF_STAFF_KICK';
