export const PERMISSIONS_AUTO_SELECT_MODEL = 'PERMISSIONS_AUTO_SELECT_MODEL';

export const PERMISSIONS_AUTO_SET_DATA = 'PERMISSIONS_AUTO_SET_DATA'

//cfg-file
// export const PERMISSIONS_AUTO_SET_RESPONSIBLE = 'PERMISSIONS_AUTO_SET_RESPONSIBLE';

export const PERMISSIONS_AUTO_CHANGE_OPTION = 'PERMISSIONS_AUTO_CHANGE_OPTION';

export const PERMISSIONS_AUTO_CHANGE_PERMISSION = 'PERMISSIONS_AUTO_CHANGE_PERMISSION';