export const PERMISSIONS_ROLES_PERMISSIONS_SET = 'PERMISSIONS_ROLES_SET';
export const PERMISSIONS_PERMISSIONS_SET = 'PERMISSIONS_PERMISSIONS_SET';
export const PERMISSIONS_PERMISSION_CHANGE = 'PERMISSIONS_PERMISSION_CHANGE';

export const PERMISSIONS_ROLE_SELECT = 'PERMISSIONS_ROLE_SELECT';
export const PERMISSIONS_ROLE_REMOVE = 'PERMISSIONS_ROLE_REMOVE';

export const PERMISSIONS_ROLE_SET_INFO = 'PERMISSIONS_ROLE_SET_INFO';

export const PERMISSIONS_TAB_OPEN = 'PERMISSIONS_TAB_OPEN';
